[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
"@uniswap-v2-core" = "1.0.1"
"@openzeppelin-contracts" = "5.0.2"
"@prb-math" = "4.0.3"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"
"@uniswap-v3-periphery" = "1.4.4"
